=== modelfitters/fittino/input/InputFile.dtd
<!ELEMENT InputFile (ExecutionMode,
                     Model,
                     Optimizer,
                     ParticleSwarmOptimizer,
                     SimulatedAnnealingOptimizer,
                     GeneticAlgorithmOptimizer) >

<!ELEMENT ExecutionMode EMPTY>
<!ATTLIST ExecutionMode
  Mode CDATA #REQUIRED
>

<!ELEMENT Model EMPTY>
<!ATTLIST Model
  ModelType CDATA #IMPLIED
  A0        CDATA #IMPLIED
  M0        CDATA #IMPLIED
  M12       CDATA #IMPLIED
  TanBeta   CDATA #IMPLIED
  X         CDATA #IMPLIED
  Y         CDATA #IMPLIED
>

<!ELEMENT Optimizer EMPTY>
<!ATTLIST Optimizer
  AbortCriterium     CDATA #REQUIRED
  NumberOfIterations CDATA #REQUIRED
  OptimizerType      CDATA #REQUIRED
>

<!ELEMENT ParticleSwarmOptimizer EMPTY>
<!ATTLIST ParticleSwarmOptimizer
  C1                CDATA #REQUIRED
  C2                CDATA #REQUIRED
  NumberOfParticles CDATA #REQUIRED
>

<!ELEMENT SimulatedAnnealingOptimizer EMPTY>
<!ATTLIST SimulatedAnnealingOptimizer
  InitialTemperature         CDATA #REQUIRED
  TemperatureReductionFactor CDATA #REQUIRED
>


<!ELEMENT GeneticAlgorithmOptimizer EMPTY>
<!ATTLIST GeneticAlgorithmOptimizer
  MutationRate         CDATA #REQUIRED
  SizeOfPopulation     CDATA #REQUIRED
>

=== modelfitters/fittino/input/Example.Optimization.in.xml
<?xml version="1.0" encoding='UTF-8'?>

<!-- $Id: Example.Optimization.in.xml 1280 2013-03-28 11:23:49Z uhlenbrock@PHYSIK.UNI-BONN.DE $ -->

<!--#########################################################################-->
<!--                                                                         -->
<!-- Project     Fittino - A SUSY Parameter Fitting Package                  -->
<!--                                                                         -->
<!-- File        Example.Optimization.in.xml                                 -->
<!--                                                                         -->
<!-- Description Optimization example                                        -->
<!--                                                                         -->
<!-- Authors     Mathias Uhlenbrock  <uhlenbrock@physik.uni-bonn.de>         -->
<!--                                                                         -->
<!-- Licence     This program is free software; you can redistribute it      -->
<!--             and/or modify it under the terms of the GNU General Public  -->
<!--             License as published by the Free Software Foundation;       -->
<!--             either version 3 of he License, or (at your option) any     -->
<!--             later version.                                              -->
<!--                                                                         -->
<!--#########################################################################-->

<!DOCTYPE InputFile PUBLIC "" "InputFile.dtd">

<InputFile>

  <VerbosityLevel
   Level = "ALWAYS"
   />

  <ExecutionMode
   Mode = "OPTIMIZATION"
   />

  <Model
   ModelType  = "Rosenbrock"
   Dimensions = "2"
   X1         = "2.56"
   X2         = "-1.54"
   />

  <Optimizer
   AbortCriterium     = "1.e-5"
   NumberOfIterations = "500"
   OptimizerType      = "SimulatedAnnealing"
   />

  <!--
   Configuration example for the genetic algorithm optimizer.
   -->

  <GeneticAlgorithmOptimizer
   MutationRate      = "0.5"
   SizeOfPopulation  = "100"
   />

  <!--
   Configuration example for the particle swarm optimizer.
   -->

  <ParticleSwarmOptimizer
   C1                = "0.01"
   C2                = "0.01"
   NumberOfParticles = "100"
   />

  <!--
   Configuration example for the simulated annealing optimizer.
   -->

  <SimulatedAnnealingOptimizer
   InitialTemperature         = "600."
   TemperatureReductionFactor = "0.5"
   />

</InputFile>
